name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123456

    runs-on: ubuntu-latest

    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola mundo"

      - name: "Mostrando variables de entorno"
        run: |
          echo "Valor de platform: ${{env.platform}}"
          echo "Valor de region: ${{env.region}}"
          echo "Valor de account: ${{env.account}}"
