name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123456

      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}

    runs-on: ubuntu-latest

    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola mundo"

      - name: "Mostrando variables de entorno"
        if: ${{ env.platform == 'azure'}}
        run: |
          echo "Valor de platform: ${{env.platform}}"
          echo "Valor de region: ${{env.region}}"
          echo "Valor de account: ${{env.account}}"

      - name: "Mostrando variables por defecto"
        run: | # | significa que tiene varios pasos
          echo "Evento: ${{toJSON(github.event)}}"
          echo "GitHub actor $GITHUB_ACTOR"
          echo "Repositorio $GITHUB_REPOSITORY"

      - name: "Mostrando valores si el usuario es correcto"
        if: ${{ env.username != '' && env.password != ''}}
        run: |
          echo "Si existe un usuario"
